<!-- SACAPI (SISTEMA AUTOMTIZADO PARA EL CONTROL ADMINISTRATIVO DEL PROGRAMA DE INGLES VERSION 2.0) -->
<!-- 
    ACTUALIZACION 2.0.1
        ->REVISIÓN DE BASE DE DATOS 
            ->CORRECION Y ACTUALIZACION DE TABALAS 
            -> SE AÑADIERON LAS TABALAS
                {
                    -> CARRERAS
                    -> FACULTADES
                    -> GENERACIONES 
                }
        ->CORRECION DE ERRORES DE INTERFAZ
    ACTUALIZACION 2.0.2
        ->SE AÑADIO EL MODULO JEFES DE CARRERA
            ->SE AÑADIO FORMULARIO PARA REGISTRO/MODIFICACION DE JEFES DE CARRERA
        ->MODIFICACION DE LA BASE DE DATOS
            ->SE ELIMINARON TABLAS INESESARIAS
            ->SE RESTRUCTURO LA TABLA DE PROFESORES
        ->CORRECION DE ERRORES DE INTERFAZ
    ACTUALIZACION 2.0.3
        ->RESTRUCTURACION DE MENU PRINCIPAL
        ->CORRECION DE MODULO DE PROFESORES ( SEPARADOS POR TIPO DE PROFESOR )
            ->CORRECION DE FORMULARIOS PARA PROFESORES
        ->OPTIMIZACION DEL CODIGO ( SE ELIMINO CODIGO INCESARIO, CODIGO OBSOLETO )
        ->MODIFICACION REPORTE DE ALUMNO 
            ->SE ACTUALIZO EL REPORTE QUE SE IMPRIME PARA EL ALUMNO
        ->MODIFICACION/REGISTRO DE DATOS ( ALUMNOS, RESULTADOS, PROFESORES )
    ACTUALIZACION 2.0.4
        ->

 -->